-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 10:15:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `rutPaciente` BIGINT NOT NULL,
  `nombrePac` VARCHAR(45) NOT NULL,
  `sexo` TINYINT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `rangoEtario` INT NOT NULL,
  `cantAtenRec` INT NOT NULL,
  PRIMARY KEY (`rutPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `rutMedico` BIGINT NOT NULL,
  `nombreMed` VARCHAR(45) NOT NULL,
  `fechaContratacion` DATE NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `valorConsulta` INT NOT NULL,
  PRIMARY KEY (`rutMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atencion` (
  `numAtencion` INT NOT NULL,
  `fechaHrAten` DATETIME NOT NULL,
  `pacienteAtendido` VARCHAR(45) NOT NULL,
  `medicoTratante` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `rangoFechas` INT NOT NULL,
  `meses` DATE NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `Paciente_rutPaciente` BIGINT NOT NULL,
  `Medico_rutMedico` BIGINT NOT NULL,
  PRIMARY KEY (`numAtencion`),
  INDEX `fk_Atencion_Paciente_idx` (`Paciente_rutPaciente` ASC),
  INDEX `fk_Atencion_Medico1_idx` (`Medico_rutMedico` ASC),
  CONSTRAINT `fk_Atencion_Paciente`
    FOREIGN KEY (`Paciente_rutPaciente`)
    REFERENCES `mydb`.`Paciente` (`rutPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atencion_Medico1`
    FOREIGN KEY (`Medico_rutMedico`)
    REFERENCES `mydb`.`Medico` (`rutMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
